### PR TITLE
Rimworld's DLLs probably shouldn't be here

### PR DESCRIPTION
**Pull request by TehJoE**
Kind of a copyright issue there. I had added them to .gitignore, but didn't realize they were already in the repository!

### CODE REVIEW

**Comment by noone57** [comment]
Merged. Also, reading more about 'Organization', I thought this would actually be perfect for what we need. I am still the "owner", but now that you are a member of the Developers team, you ought to be able to push commits yourself, as well as create releases. 

I am not 100% sure about the release part, can you confirm this ?

**Comment by TehJoE** [comment]
It appears so, I can see and have an option to confirm the Alpha 9 draft
listed in the repository now - I'm actually looking into a way to create a
release that just excludes source code for the majority of the users who
aren't interested in having that as part of their download. If I don't find
anything in the next few minutes I'll just post the release, source and all.

**Comment by noone57** [comment]
The way I did it previously was to compress all the required files myself (everything minus source code), and then simply add it manually to the release (there's a drag and drop area at the bottom).

**Comment by noone57** [comment]
And for the RW forum: I have not found a way to transfer you ownership of the first post. 
You could create a new dedicated post, but it is not a great solution if we keep switching ownership, new people arrive/leave, etc ... 

In fact, the best might actually be to create a profile for the A2Bcorp itself on the forum. That way, either you or I (or any future collaborator) could upgrade the first post as required. That'd be elegant, ensure that the main A2B post remains accessible in the future, etc ... 

Would you agree ? If yes, I'll create the new alias + password and prep it for the next release.

**Comment by TehJoE** [comment]
Looks like any automated solution is gonna be impractical, I just uploaded
it manually. And the forum account deal sounds like a good plan to me, as
it ensures access even if we end up having a revolving door of primary
contributors.

**Pull request merged**
